"""
Secure Cypher Query Validator for Neo4j GraphRAG.

Ensures Neo4j queries generated by LLMs are read-only and prevents write,
update, delete, and administrative operations.
"""

from __future__ import annotations

import re


def validate_cypher_query(cypher: str) -> None:
    """
    Validate that a Cypher query is read-only and safe.
    
    Raises:
        ValueError: If the query contains writing or administrative statements.
    """
    if not cypher or not isinstance(cypher, str):
        raise ValueError("Cypher query must be a non-empty string.")

    # Pre-process the Cypher query: strip comments (//) to avoid bypasses using comments
    cleaned_lines = []
    for line in cypher.splitlines():
        # Strip comments
        if "//" in line:
            line = line.split("//")[0]
        cleaned_lines.append(line.strip())
    
    cleaned_cypher = " ".join(cleaned_lines).strip()
    upper_cypher = cleaned_cypher.upper()

    # 1. Blocked keywords check (destructive write queries)
    blocked_keywords = [
        "CREATE",
        "MERGE",
        "DELETE",
        "DETACH",
        "SET",
        "REMOVE",
        "DROP",
        "LOAD CSV",
    ]
    for keyword in blocked_keywords:
        pattern = rf"\b{re.escape(keyword)}\b"
        if re.search(pattern, upper_cypher):
            from security.audit.logger import log_security_violation
            err_msg = f"Unsafe Cypher blocked: query contains write/modification keyword '{keyword}'."
            log_security_violation("UNSAFE_CYPHER", f"{err_msg} Query: {cypher}")
            raise ValueError(err_msg)

    # 2. Enforce starting with read-only keywords
    # Allowed starting operations: MATCH, OPTIONAL MATCH, WITH, RETURN, UNWIND, SHOW
    allowed_prefixes = ("MATCH", "OPTIONAL MATCH", "WITH", "RETURN", "UNWIND", "SHOW")
    if not upper_cypher.startswith(allowed_prefixes):
        from security.audit.logger import log_security_violation
        err_msg = "Only read-only Cypher queries are allowed. Query must start with MATCH, WITH, etc."
        log_security_violation("UNSAFE_CYPHER", f"{err_msg} Query: {cypher}")
        raise ValueError(err_msg)

    # 3. Check for unauthorized procedure CALLs (system calling APIs)
    blocked_calls = ["CALL DBMS", "CALL APOC"]
    for call in blocked_calls:
        if call in upper_cypher:
            from security.audit.logger import log_security_violation
            err_msg = f"Unsafe Cypher blocked: query contains unauthorized procedure '{call}'."
            log_security_violation("UNSAFE_CYPHER", f"{err_msg} Query: {cypher}")
            raise ValueError(err_msg)
