"""
Shared LangGraph state passed between orchestration nodes.
"""

from typing import Any, NotRequired, TypedDict


class AgentState(TypedDict):
    """State object threaded through the orchestration graph."""

    user_query: str
    original_query: NotRequired[str]
    detected_language: NotRequired[str]
    language_hint: NotRequired[str]

    domain: str
    coarse_domain: NotRequired[str]

    task: str
    confidence: float

    agent_response: str
    final_response: str

    authenticated_user: NotRequired[dict[str, Any]]
    authenticated_user_id: NotRequired[str]
    authenticated_email: NotRequired[str]
    authenticated_name: NotRequired[str]
    authenticated_role_id: NotRequired[int | None]
    authenticated_courier_id: NotRequired[str]

    # Courier identity binding. For COURIER users only:
    #   JWT courier_id claim (authenticated_courier_id) -> bound_courier_id (direct).
    # The JWT identity is authoritative; no name resolution is performed. Centralized
    # resource authorization is built on bound_courier_id.
    # bound_courier_name is retained for tracing/diagnostics only.
    bound_courier_name: NotRequired[str | None]
    bound_courier_id: NotRequired[str | None]

    logistics_session: NotRequired[dict[str, Any]]
    inventory_session: NotRequired[dict[str, Any]]
    pending_clarification_session: NotRequired[dict[str, Any] | None]

    user_role: NotRequired[str]

    access_denied: NotRequired[bool]
    authorization_denied: NotRequired[bool]
    authorized: NotRequired[bool]

    # Deferred authorization (ALLOW / DENY / DEFER). DEFER means ownership cannot
    # yet be evaluated because scope context is missing; the turn continues to
    # parameter_preparation, which collects the missing scope via HITL, and
    # authorize re-evaluates on the resume pass.
    authorization_status: NotRequired[str | None]
    authorization_deferred: NotRequired[bool]

    # Authorization scope handed to execution. None for ADMIN/LOGISTICS; for a
    # COURIER it pins {"courier_id": bound_courier_id} so dynamic execution is
    # confined to the courier's own data.
    authorization_scope: NotRequired[dict[str, Any] | None]

    # FIXED
    authorized_domain: NotRequired[str | None]

    classification_source: NotRequired[str]

    # FIXED
    clarification_stage: NotRequired[str | None]

    entities: NotRequired[dict[str, str]]
    prefetched_order_route: NotRequired[dict[str, Any]]

    missing_fields: NotRequired[list[str]]
    missing_required_parameters: NotRequired[bool]

    function_name: NotRequired[str | None]
    payload: NotRequired[dict[str, Any]]

    clarification_needed: NotRequired[bool]
    clarification_failed: NotRequired[bool]

    # ALREADY CORRECT
    clarification_type: NotRequired[str | None]

    # ALREADY CORRECT
    clarification_question: NotRequired[str | None]

    execution_status: NotRequired[str | None]
    execution_error: NotRequired[str | None]

    # Cypher generated by the dynamic GraphDB path (tracing/diagnostics only).
    generated_cypher: NotRequired[str | None]

    ml_payload_partial: NotRequired[dict[str, Any]]

    trace_id: NotRequired[str]

    # Semantic cache (Redis). cache_hit short-circuits execution to the formatter;
    # cache_response holds the cached final_response served on a hit.
    cache_hit: NotRequired[bool]
    cache_response: NotRequired[Any]